prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "geth"
    metrics_path: /debug/metrics/prometheus
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/geth.yml"